mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  username: YOURUSERNAME
  password: YOURPASSWORD

light:
  - platform: mqtt
    schema: json
    name: "Stepenice LED"
    state_topic: "paxyhome/stepenice"
    command_topic: "paxyhome/stepenice/set"
    effect: true
    effect_list:
      - light-in
      - light-out
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0


automation: 
- id: -Stepeniste- Upali svetlo na pokret
  alias: -Stepeniste- Upali svetlo na pokret
  hide_entity: false
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.motion_sensor_158d000121a0b3
  condition:
    condition: state
    entity_id: input_boolean.auto_light
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.hodnik
      brightness: 255
      rgb_color:
      - 255
      - 255
      - 255
      transition: 0
  - service: light.turn_on
    data:
      entity_id: light.stepenice_led
      effect: light-in
- id: -Stepeniste- Ugasi svetlo u hodniku kada nema nikog
  alias: -Stepeniste- Ugasi svetlo u hodniku kada nema nikog
  hide_entity: false
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121a0b3
    to: 'off'
    from: 'on'
  condition:
    condition: state
    entity_id: input_boolean.auto_light
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.hodnik
  - service: light.turn_on
    data:
      entity_id: light.stepenice_led
      effect: light-out
